/** Maps human-readable asset labels (quiz checkboxes + user-typed tickers) to CoinGecko metadata. */
export const ASSET_MAP: Record<
  string,
  { id: string; symbol: string; name: string }
> = {
  // Quiz checkbox labels
  "Bitcoin (BTC)": { id: "bitcoin", symbol: "BTC", name: "Bitcoin" },
  "Ethereum (ETH)": { id: "ethereum", symbol: "ETH", name: "Ethereum" },
  "Solana (SOL)": { id: "solana", symbol: "SOL", name: "Solana" },
  XRP: { id: "ripple", symbol: "XRP", name: "XRP" },
  "Dogecoin (DOGE)": { id: "dogecoin", symbol: "DOGE", name: "Dogecoin" },
  // Common tickers users might type
  BTC: { id: "bitcoin", symbol: "BTC", name: "Bitcoin" },
  ETH: { id: "ethereum", symbol: "ETH", name: "Ethereum" },
  SOL: { id: "solana", symbol: "SOL", name: "Solana" },
  DOGE: { id: "dogecoin", symbol: "DOGE", name: "Dogecoin" },
  ADA: { id: "cardano", symbol: "ADA", name: "Cardano" },
  Cardano: { id: "cardano", symbol: "ADA", name: "Cardano" },
  DOT: { id: "polkadot", symbol: "DOT", name: "Polkadot" },
  Polkadot: { id: "polkadot", symbol: "DOT", name: "Polkadot" },
  MATIC: { id: "matic-network", symbol: "MATIC", name: "Polygon" },
  Polygon: { id: "matic-network", symbol: "MATIC", name: "Polygon" },
  LINK: { id: "chainlink", symbol: "LINK", name: "Chainlink" },
  Chainlink: { id: "chainlink", symbol: "LINK", name: "Chainlink" },
  AVAX: { id: "avalanche-2", symbol: "AVAX", name: "Avalanche" },
  Avalanche: { id: "avalanche-2", symbol: "AVAX", name: "Avalanche" },
  ATOM: { id: "cosmos", symbol: "ATOM", name: "Cosmos" },
  Cosmos: { id: "cosmos", symbol: "ATOM", name: "Cosmos" },
  LTC: { id: "litecoin", symbol: "LTC", name: "Litecoin" },
  Litecoin: { id: "litecoin", symbol: "LTC", name: "Litecoin" },
  UNI: { id: "uniswap", symbol: "UNI", name: "Uniswap" },
  Uniswap: { id: "uniswap", symbol: "UNI", name: "Uniswap" },
  BCH: { id: "bitcoin-cash", symbol: "BCH", name: "Bitcoin Cash" },
  "Bitcoin Cash": { id: "bitcoin-cash", symbol: "BCH", name: "Bitcoin Cash" },
  TRX: { id: "tron", symbol: "TRX", name: "TRON" },
  TRON: { id: "tron", symbol: "TRX", name: "TRON" },
  TON: { id: "the-open-network", symbol: "TON", name: "Toncoin" },
  Toncoin: { id: "the-open-network", symbol: "TON", name: "Toncoin" },
  SHIB: { id: "shiba-inu", symbol: "SHIB", name: "Shiba Inu" },
  "Shiba Inu": { id: "shiba-inu", symbol: "SHIB", name: "Shiba Inu" },
  PEPE: { id: "pepe", symbol: "PEPE", name: "Pepe" },
  SUI: { id: "sui", symbol: "SUI", name: "Sui" },
  APT: { id: "aptos", symbol: "APT", name: "Aptos" },
  Aptos: { id: "aptos", symbol: "APT", name: "Aptos" },
  NEAR: { id: "near", symbol: "NEAR", name: "NEAR Protocol" },
  "NEAR Protocol": { id: "near", symbol: "NEAR", name: "NEAR Protocol" },
  FIL: { id: "filecoin", symbol: "FIL", name: "Filecoin" },
  Filecoin: { id: "filecoin", symbol: "FIL", name: "Filecoin" },
  ICP: { id: "internet-computer", symbol: "ICP", name: "Internet Computer" },
  ARB: { id: "arbitrum", symbol: "ARB", name: "Arbitrum" },
  Arbitrum: { id: "arbitrum", symbol: "ARB", name: "Arbitrum" },
  OP: { id: "optimism", symbol: "OP", name: "Optimism" },
  Optimism: { id: "optimism", symbol: "OP", name: "Optimism" },
  XMR: { id: "monero", symbol: "XMR", name: "Monero" },
  Monero: { id: "monero", symbol: "XMR", name: "Monero" },
  MORPHO: { id: "morpho", symbol: "MORPHO", name: "Morpho" },
  KCS: { id: "kucoin-shares", symbol: "KCS", name: "KuCoin Token" },
  "KuCoin Token": { id: "kucoin-shares", symbol: "KCS", name: "KuCoin Token" },
};
